allowBuilds:
  electron-winstaller: true
  electron: true
  esbuild: true
  node-mac-permissions: true
  uiohook-napi: true
allowedDeprecatedVersions:
  '@electron-webauthn/native': 0.0.6
  boolean: 3.2.0
  glob: 7.2.3
  inflight: 1.0.6
  rimraf: 2.6.3
  tar: 6.2.1
blockExoticSubdeps: true
minimumReleaseAge: 1440
strictDepBuilds: true
trustPolicy: no-downgrade
